========================================
Результат без параметрів: 
No URL passed to function
========================================
Результат з правильною URL: 
Time is:  08:26:25 AM
Date is:  11-15-2020
good night
============================= test session starts ==============================
platform linux -- Python 3.8.5, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: /home/oleh/TPIS/Lab2
collected 4 items

tests/tests.py ..F.                                                      [100%]

=================================== FAILURES ===================================
___________________________ TestClass.test_home_work ___________________________

self = <tests.tests.TestClass testMethod=test_home_work>

    def test_home_work(self):
        # Ваш захист
        self.assertEqual(home_work("http://date.jsontest.com/"), True)
>       self.assertEqual(home_work("http://date.jsontest.com/"), False)
E       AssertionError: True != False

tests/tests.py:25: AssertionError
----------------------------- Captured stdout call -----------------------------
good night
good night
=========================== short test summary info ============================
FAILED tests/tests.py::TestClass::test_home_work - AssertionError: True != False
========================= 1 failed, 3 passed in 1.56s ==========================
